openapi: 3.0.3
info:
  title: Bank Lock Request API
  description: API for managing bank contract lock requests.
  version: 1.0.0
servers:
  - url: https://example.com/api
paths:
  /lock-request/create:
    post:
      summary: Create a bank contract lock request
      operationId: createBankContractLock
      requestBody:
        required: true
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/BankContractLockRequestFSCreateRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/BankContractLockRequestFSCreateConfirmation'
  /lock-request/update:
    post:
      summary: Update a bank contract lock request
      operationId: updateBankContractLock
      requestBody:
        required: true
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/BankContractLockRequestFSUpdateRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/BankContractLockRequestFSUpdateConfirmation'
components:
  schemas:
    BusinessDocumentMessageHeader:
      type: object
      properties:
        MessageID:
          type: string
          minLength: 1
          maxLength: 35
        CreationDateTime:
          type: string
          format: date-time
        SenderID:
          type: string
          minLength: 1
          maxLength: 60
        ReceiverID:
          type: string
          minLength: 1
          maxLength: 60
    BankContractLockRequestFSCreateRequest:
      type: object
      properties:
        MessageHeader:
          $ref: '#/components/schemas/BusinessDocumentMessageHeader'
        BankContractLockRequest:
          type: object
          properties:
            ID:
              type: string
              minLength: 1
              maxLength: 12
            UserStatusCode:
              type: string
              minLength: 1
              maxLength: 2
            ValidityEndDate:
              type: string
              format: date
    BankContractLockRequestFSCreateConfirmation:
      type: object
      properties:
        MessageHeader:
          $ref: '#/components/schemas/BusinessDocumentMessageHeader'
        BankContractLockResponse:
          type: object
          properties:
            ID:
              type: string
              minLength: 1
              maxLength: 12
            Status:
              type: string
              minLength: 1
              maxLength: 20
    BankContractLockRequestFSUpdateRequest:
      type: object
      properties:
        MessageHeader:
          $ref: '#/components/schemas/BusinessDocumentMessageHeader'
        BankContractLockRequest:
          type: object
          properties:
            ID:
              type: string
              minLength: 1
              maxLength: 12
            ChangeStateID:
              type: string
              minLength: 1
              maxLength: 40
            UserStatusCode:
              type: string
              minLength: 1
              maxLength: 2
            ValidityEndDate:
              type: string
              format: date
    BankContractLockRequestFSUpdateConfirmation:
      type: object
      properties:
        MessageHeader:
          $ref: '#/components/schemas/BusinessDocumentMessageHeader'
        BankContractLockResponse:
          type: object
          properties:
            ID:
              type: string
              minLength: 1
              maxLength: 12
            Status:
              type: string
              minLength: 1
              maxLength: 20
    StandardMessageFault:
      type: object
      properties:
        standard:
          type: object
          properties:
            faultText:
              type: string
            faultUrl:
              type: string
            faultDetail:
              type: array
              items:
                type: object
                properties:
                  message:
                    type: string
                  code:
                    type: string
